# Generated by Django 5.0.3 on 2024-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_purchase_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
