# Generated by Django 5.0.3 on 2024-03-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menuitem_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
