# Generated by Django 5.0.3 on 2024-03-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_purchasehistory_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='ingredient',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main.ingredient'),
        ),
    ]
